const ADD_INGREDIENT = 'ADD_INGREDIENT';
const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';


export {ADD_INGREDIENT, DELETE_INGREDIENT,INCREMENT, DECREMENT};
